version: '3.7'

services:
  dev:
    build:
      context: ./images/dev/
      target: DEV
    volumes:
      - .:/app/
  docs:
    build:
      context: ./images/dev/
      target: DOCS
    volumes:
      - .:/app/

  git-crypt:
    build:
      context: ./images/git-crypt/
