version: '3.7'

services:
  dev:
    image: andyAugustin/dev
    build:
      context: ./images/dev/
      target: DEV
    volumes:
      - .:/app/
    working_dir: /app/

  docs:
    image: andyAugustin/docs
    build:
      context: ./images/docs/
      target: DOCS
    volumes:
      - .:/app/
    working_dir: /app/

  git-crypt:
    image: andyAugustin/git-crypt
    build:
      context: ./images/git-crypt/

  git-secrets:
    image: andyAugustin/git-secrets
    build:
      context: ./images/git-secrets/
    volumes:
      - .:/app/
    working_dir: /app/

  container-structure-test:
    image: gcr.io/gcp-runtimes/container-structure-test:latest
    volumes:
      - .:/app/
      - /var/run/docker.sock:/var/run/docker.sock
    working_dir: /app/
