version: '3.7'

services:
  dev:
    build:
      context: ./images/dev/
      target: DEV
    volumes:
      - .:/app/
    working_dir: /app/

  docs:
    build:
      context: ./images/dev/
      target: DOCS
    volumes:
      - .:/app/
    working_dir: /app/

  git-crypt:
    build:
      context: ./images/git-crypt/

  git-secrets:
    build:
      context: ./images/git-secrets/
