name: Lint

on: [push]

jobs:

  lint:

    runs-on: ubuntu-latest

    steps:
    -
      name: checkout
      uses: actions/checkout@v2
    -
      name: markdownlint
      run: make markdownlint
    -
      name: prune
      run: make prune
